import Link from "next/link";
import { ArrowRight, Sparkles, TrendingDown, TrendingUp } from "lucide-react";
import { Logo } from "@/components/finsight/logo";
import { Button } from "@/components/ui/button";
import { VerdictChip, riskLevelLabel } from "@/components/finsight/verdict-chip";

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

interface DemoReport {
  ticker: string;
  job_id: string;
  summary: string | null;
  risk_score: number | null;
  generated_at: string | null;
  executive_summary?: string | null;
  risk_rationale?: string | null;
  risk_level?: string | null;
  bull_case?: string | null;
  bear_case?: string | null;
  valuation_rating?: string | null;
  confidence?: string | null;
}

async function fetchDemo(ticker: string): Promise<DemoReport | null> {
  try {
    const res = await fetch(
      `${API_BASE}/demo/${encodeURIComponent(ticker.toUpperCase())}`,
      { cache: "no-store" },
    );
    if (!res.ok) return null;
    return (await res.json()) as DemoReport;
  } catch {
    return null;
  }
}

export default async function DemoPage({
  params,
}: {
  params: Promise<{ ticker: string }>;
}) {
  const { ticker } = await params;
  const sym = ticker.toUpperCase();
  const data = await fetchDemo(sym);

  return (
    <main className="flex min-h-screen flex-col bg-[var(--color-background)]">
      <header className="mx-auto flex w-full max-w-5xl items-center justify-between px-6 py-5">
        <Logo size="md" />
        <nav className="flex items-center gap-2 text-sm">
          <Button variant="ghost" size="sm" asChild>
            <Link href="/login">Sign in</Link>
          </Button>
          <Button variant="primary" size="sm" asChild>
            <Link href="/login">
              Create free account <ArrowRight className="h-4 w-4" />
            </Link>
          </Button>
        </nav>
      </header>

      <section className="mx-auto w-full max-w-3xl flex-1 px-6 pb-16">
        <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-1 text-xs uppercase tracking-wider text-[var(--color-muted)]">
          <Sparkles className="h-3 w-3 text-[var(--color-accent)]" />
          Live demo · {sym}
        </div>
        <h1 className="text-balance text-3xl font-semibold leading-tight tracking-tight text-[var(--color-foreground)] sm:text-4xl">
          {data
            ? `Sample research report for ${sym}`
            : `${sym} demo`}
        </h1>
        <p className="mt-3 max-w-2xl text-sm text-[var(--color-muted-strong)]">
          A real report generated by FinSight from {sym}&apos;s SEC filings and live
          market data. No sign-up required to read this page.
        </p>
        <ul className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-[var(--color-muted-strong)]">
          <li className="inline-flex items-center gap-1.5">
            <span className="h-1.5 w-1.5 rounded-full bg-[var(--color-accent)]" />
            Free — no credit card
          </li>
          <li className="inline-flex items-center gap-1.5">
            <span className="h-1.5 w-1.5 rounded-full bg-[var(--color-accent)]" />
            Email + password only
          </li>
          <li className="inline-flex items-center gap-1.5">
            <span className="h-1.5 w-1.5 rounded-full bg-[var(--color-accent)]" />
            Cancel any time
          </li>
        </ul>

        {!data && (
          <div className="mt-10 rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface)] p-8 text-center">
            <p className="text-sm text-[var(--color-muted-strong)]">
              No demo report is available yet for {sym}. Try one of these:
            </p>
            <div className="mt-4 flex flex-wrap justify-center gap-2">
              {["AAPL", "NVDA", "TSLA", "MSFT"].map((t) => (
                <Link
                  key={t}
                  href={`/demo/${t}`}
                  className="rounded-full border border-[var(--color-border)] bg-[var(--color-background)] px-3 py-1 font-mono text-xs text-[var(--color-foreground)] hover:border-[var(--color-accent)] hover:text-[var(--color-accent)]"
                >
                  {t}
                </Link>
              ))}
            </div>
            <Button variant="primary" size="md" asChild className="mt-6">
              <Link href="/login">
                Sign up to generate one <ArrowRight className="h-4 w-4" />
              </Link>
            </Button>
          </div>
        )}

        {data && (
          <div className="mt-10 space-y-8">
            {/* Executive summary card with verdict */}
            <div className="rounded-[var(--radius-lg)] border border-[var(--color-accent)]/20 bg-[var(--color-accent)]/5 p-6">
              <div className="mb-3 flex flex-wrap items-center justify-between gap-3">
                <div className="flex items-center gap-2">
                  <Sparkles className="h-4 w-4 text-[var(--color-accent)]" />
                  <span className="text-xs font-semibold uppercase tracking-wider text-[var(--color-accent)]">
                    Executive Summary
                  </span>
                </div>
                <VerdictChip
                  size="md"
                  inputs={{
                    risk_score: data.risk_score ?? null,
                    valuation_rating: data.valuation_rating ?? null,
                    confidence: data.confidence ?? null,
                  }}
                />
              </div>
              <p className="text-base font-medium leading-relaxed text-[var(--color-foreground)]">
                {data.executive_summary || data.summary || "—"}
              </p>
            </div>

            {/* Risk one-liner */}
            {data.risk_score != null && (
              <div className="flex items-baseline gap-3 rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-surface)] p-4">
                <span className="rounded-md border border-[var(--color-border)] bg-[var(--color-surface-elevated)] px-2 py-0.5 font-mono text-xs font-semibold text-[var(--color-foreground)]">
                  {riskLevelLabel(data.risk_score)}
                </span>
                <span className="text-xs text-[var(--color-muted)]">
                  {data.risk_score}/100
                </span>
                <span className="flex-1 text-sm text-[var(--color-foreground)]">
                  {data.risk_rationale ?? ""}
                </span>
              </div>
            )}

            {/* Bull / bear preview */}
            {(data.bull_case || data.bear_case) && (
              <div className="grid gap-4 sm:grid-cols-2">
                {data.bull_case && (
                  <div
                    className="rounded-[var(--radius-md)] border p-5"
                    style={{
                      borderColor:
                        "color-mix(in oklab, var(--color-accent) 40%, transparent)",
                      backgroundColor:
                        "color-mix(in oklab, var(--color-accent) 5%, transparent)",
                    }}
                  >
                    <div className="mb-2 flex items-center gap-2 text-sm font-semibold text-[var(--color-accent)]">
                      <TrendingUp className="h-4 w-4" />
                      Bull case
                    </div>
                    <p className="text-sm leading-relaxed text-[var(--color-foreground)]">
                      {data.bull_case}
                    </p>
                  </div>
                )}
                {data.bear_case && (
                  <div
                    className="rounded-[var(--radius-md)] border p-5"
                    style={{
                      borderColor:
                        "color-mix(in oklab, var(--color-danger) 40%, transparent)",
                      backgroundColor:
                        "color-mix(in oklab, var(--color-danger) 5%, transparent)",
                    }}
                  >
                    <div className="mb-2 flex items-center gap-2 text-sm font-semibold text-[var(--color-danger)]">
                      <TrendingDown className="h-4 w-4" />
                      Bear case
                    </div>
                    <p className="text-sm leading-relaxed text-[var(--color-foreground)]">
                      {data.bear_case}
                    </p>
                  </div>
                )}
              </div>
            )}

            {/* CTA */}
            <div className="rounded-[var(--radius-lg)] border border-[var(--color-accent)]/40 bg-[color:color-mix(in_oklab,var(--color-accent)_8%,transparent)] p-8 text-center">
              <h2 className="text-xl font-semibold text-[var(--color-foreground)]">
                Run this on any public company in 30 seconds
              </h2>
              <p className="mx-auto mt-2 max-w-lg text-sm text-[var(--color-muted-strong)]">
                Create a free account to unlock full reports — SWOT, catalysts,
                cited 10-K excerpts, peer comparison, and follow-up chat. No
                credit card needed.
              </p>
              <div className="mt-5 flex flex-wrap items-center justify-center gap-3">
                <Button variant="primary" size="lg" asChild>
                  <Link href="/login">
                    Create free account <ArrowRight className="h-4 w-4" />
                  </Link>
                </Button>
                <Button variant="ghost" size="lg" asChild>
                  <Link href="/login">I already have an account</Link>
                </Button>
              </div>
              <p className="mt-3 text-[11px] text-[var(--color-muted)]">
                Free forever for personal research. We never sell your data.
              </p>
            </div>
          </div>
        )}
      </section>

      <footer className="border-t border-[var(--color-border)]">
        <div className="mx-auto flex w-full max-w-5xl items-center justify-between px-6 py-6 text-xs text-[var(--color-muted)]">
          <span>© {new Date().getFullYear()} FinSight Research</span>
          <Link href="/" className="hover:text-[var(--color-accent)]">
            Back to home
          </Link>
        </div>
      </footer>
    </main>
  );
}
